### ISSUE TITLE
Licence file in the repo

### ISSUE THREAD

**Issue by samizdis** [nextgis/pygdal#30]
Hi there,

Pypi says that this repo is released under the MIT licence (https://pypi.python.org/pypi/pygdal/2.2.1.3) but there doesn't seem to be a `LICENCE` or `COPYING` file in the repo. At the moment I suspect this means that technically it's not released under any licence at all (which is probably not what you want, "If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software" https://choosealicense.com/no-license/) , since I don't think pypi has the right to just declare what your licence is.

Could you add a LICENCE file to the repo? If you're happy with the MIT licence it's just a copy-paste from https://choosealicense.com/licenses/mit/ , or if you want to look into it https://choosealicense.com/ is pretty good (but please update on pypi if you pick something else!)

Cheers!

**Comment by dezhin** [comment]
LICENSE file from GDAL added in ea795803f0b1a0dc50ed586369ff90a3721e1ffb.
