### ISSUE TITLE
Python 3.X issue

### ISSUE THREAD

**Issue by drnextgis** [nextgis/pygdal#31]
@dezhin does `pygdal` is not compatible with Python 3. I'm trying to iterate overs shapefile features but get an error:

```
>>> from osgeo import ogr
>>> driver = ogr.GetDriverByName('ESRI Shapefile')
>>> dataSource = driver.Open('united_roads.shp', 0)
>>> layer = dataSource.GetLayer()
>>> for feature in layer:
...   print(feature)
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: iter() returned non-iterator of type 'Layer'
```

**Comment by drnextgis** [comment]
Workaround:

```
feat = layer.GetNextFeature()
while feat is not None:
    print(feature)
    feat = layer.GetNextFeature()
```

**Comment by dezhin** [comment]
Does it work with original gdal python bindings?


Denis Rykov <notifications@github.com> 14 ноября 2017 г. 6:20:18 ДП написал:

**Comment by drnextgis** [comment]
Yes, original bindings (located at /usr/lib/python3/dist-packages/osgeo) works as expected.

**Comment by dezhin** [comment]
This issue has been fixed in `pygdal=*.6`
