### ISSUE TITLE
ogr.Open returns None

### ISSUE THREAD

**Issue by ianbstewart** [nextgis/pygdal#32]
I'm using GDAL version 1.11.1, and I installed the corresponding version of pygdal:

`pip install pygdal=1.11.1`

The code imports fine, but when I try to open a file it returns None.

`from osgeo import gdal, ogr
pbf_file = 'path/to/file.osm.pbf'
osm = ogr.Open(pbf_file)
print(osm) # None
`

This might not be a pygdal-specific problem but just thought I would pass it on.

**Comment by drnextgis** [comment]
Cannot reproduce it here (GDAL 2.2.2):

```
>>> from osgeo import ogr
>>> pbf_file = 'RU.osm.pbf'
>>> osm = ogr.Open(pbf_file) 
>>> print(osm)
<osgeo.ogr.DataSource; proxy of <Swig Object of type 'OGRDataSourceShadow *' at 0x7f51ec900630> >
```

**Comment by BishopGIS** [comment]
First of all check if `ogrinfo` can open your pbf file.

> ogrinfo  path/to/file.osm.pbf

**Comment by drnextgis** [comment]
Please reopen if needed.
