### ISSUE TITLE
pygdal 1.11.4.3

### ISSUE THREAD

**Issue by juliermegeotube** [nextgis/pygdal#34]
Hi,
I am running a CentOS VM which has gdal 1.11.4 version installed, and I am trying to install pygdal 1.11.4.3 in a python virtualenv, but I have not gotten any success by running pip install pygdal==1.11.4.3 the closest to gdal version. I got a lot of warnings: _configtest.c:16:5: warning: conflicting types for built-in function ???
Any help on that please?
Thank you very much for your time in advance

**Comment by drnextgis** [comment]
It is only warnings. Does `pygdal` works after that?

**Comment by BishopGIS** [comment]
no feedback
