### ISSUE TITLE
How to install libgdal1 on CentOS?

### ISSUE THREAD

**Issue by andrew6850** [nextgis/pygdal#35]
I would love to use this project, but absolutely must use it on CentOS.  I'm having a tough time finding out how to install the libgdal1 dependency on CentOS.  It doesn't seem to be available in Yum repositories.  I'm happy to install it from scratch, but have no idea which instructions are valid.  Here are the ones you posted for Ubuntu:

sudo apt-get install libgdal1-dev

If anyone has tips for installing this dependency on CentOS, I would appreciate them!

Andrew

**Comment by drnextgis** [comment]
Hello Andrew. You should install EPEL repositoty for installing `gdal-devel` package:
```
$ sudo yum install epel-release
$ sudo yum install gdal-devel
```

**Comment by drnextgis** [comment]
@andrew6850 any updates?

**Comment by andrew6850** [comment]
That worked perfectly, thank you!

**Comment by Rangsan-khamkhaon** [comment]
Error:
 Problem: package gdal-devel-3.0.4-11.el8.x86_64 requires libgdal.so.26()(64bit), but none of the providers can be installed
  - package gdal-devel-3.0.4-11.el8.x86_64 requires gdal-libs(x86-64) = 3.0.4-11.el8, but none of the providers can be installed
  - conflicting requests
  - nothing provides libjson-c.so.4(JSONC_0.14)(64bit) needed by gdal-libs-3.0.4-11.el8.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
