### ISSUE TITLE
document auto-matched version

### ISSUE THREAD

**Issue by hyperknot** [nextgis/pygdal#37]
It took me a while to figure out the pip pattern to auto-matched version. 

Here is the correct way to install this library in a script:
```
pip install pygdal=="`gdal-config --version`.*"
```

Maybe this would be nice in the README? Then the whole process could be simplified one step.

**Comment by simgislab** [comment]
feel free to send a PR for pygdal'a README

**Comment by drnextgis** [comment]
Fixed via https://github.com/nextgis/pygdal/commit/78a793057d2162c292af4f6b240e19da5d5e52e2
