### ISSUE TITLE
Docstring 'slopeformat' should read 'slopeFormat'

### ISSUE THREAD

**Issue by Zeitsperre** [nextgis/pygdal#41]
https://github.com/nextgis/pygdal/blob/78a793057d2162c292af4f6b240e19da5d5e52e2/2.4.0/osgeo/gdal.py#L773

I just lost a bit of time trying to figure out how to call this option and it turns out that the reason was docstring has a typo. Really small issue but might save some poor soul in the future.

Thanks for maintaining an amazing library!

**Comment by drnextgis** [comment]
Please report it to upstream: https://github.com/OSGeo/gdal
