### ISSUE TITLE
pygdal 2.4.1 release?

### ISSUE THREAD

**Issue by eobropta** [nextgis/pygdal#42]
Just wanted to check in when pygdal 2.4.1 might be available. Homebrew on Mac OSX has updated to gdal 2.4.1 so pygdal no longer works with gdal installed through homebrew. I'm willing to help do it and make a pull request if you can provide some instruction. Thanks!

**Comment by drnextgis** [comment]
Fixed via https://github.com/nextgis/pygdal/commit/f708e309de8285576a8fef3096660c6f71cbd86a
