### ISSUE TITLE
OpenCL doesn't seem to work

### ISSUE THREAD

**Issue by Nodjo** [nextgis/pygdal#43]
I can't get OpenCL to work with gdal warp.

I'm using pygdal inside a Docker which I believe is properly set up with OpenCL as it works for opencv for example (a call to cv2.ocl.haveOpenCL() returns True).

However, gdal warp is as slow as before and my GPU remains totally unused. I've tried this set of options:
```
gdal.WarpOptions(resampleAlg=GRIORA_Lanczos,
                                        setColorInterpretation=True,
                                        warpOptions=["USE_OPENCL=TRUE"],
                                        creationOptions=["TILED=YES"],
                                        dstSRS="EPSG:4326")
```
but USE_OPENCL doesn't seem to do anything. I've tried playing around with other options without luck

Any help would be greatly appreciated !

**Comment by dezhin** [comment]
I don't think this issue is related to `pygdal`. Try to reproduce the problem with standard bindings from your OS distribution, `python-gdal` from Ubuntu for example. And reopen issue if problem is not reproducible.
