### ISSUE TITLE
Are there any plans for a 3.0.2 release? 

### ISSUE THREAD

**Issue by davekennewell** [nextgis/pygdal#45]
I'm using ubuntu 18.04 and pygdal won't install.

` __main__.GDALConfigError: Version mismatch 3.0.2 != 3.0.1`

Unfortunately the alternate solution of rolling back to `gdal-bin=2.2.3` doesn't work either. 

Thanks!

**Comment by davekennewell** [comment]
Update - I solved this by using the `ppa:ubuntugis/ppa` repo rather than the `ppa:ubuntugis/ubuntugis-unstable` repo (which of course makes sense...!)

**Comment by dezhin** [comment]
Done! 3.0.2 just uploaded to PyPi.
