### ISSUE TITLE
Optional full path to gdal-config

### ISSUE THREAD

**Issue by adieyal** [nextgis/pygdal#46]
Currently setup.py assumes that gdal-config is in the path ([https://github.com/nextgis/pygdal/blob/master/setup.py#L31](https://github.com/nextgis/pygdal/blob/master/setup.py#L31)) - this can be problematic when it isn't, e.g. using a the heroku-geo-buildpack which installs it in /app/.heroku-geo-buildpack/vendor/. 

The problem can be solved by explicitly editing the global path but it would be helpful if there was environment variable such as GDAL_CONFIG_PATH.

**Comment by dezhin** [comment]
Heroku doesn't allow to override PATH variable before running pip install? Something like this:
```$ PATH=/app/.heroku-geo-buildpack/vendor/:$PATH pip instal ...```
