### ISSUE TITLE
2.4.4 not supported, the only macOS homebrew version

### ISSUE THREAD

**Issue by hyperknot** [nextgis/pygdal#49]
Right now, the only gdal version in macOS homebrew-core is 2.4.4, and it is not supported by pygdal.

Can you add support for it?

**Comment by FreelanceDev217** [comment]
I have the same problem on Mac. Please consider supporting GDAL 2.4.4.
I tried to use `pygdal==2.4.2.x` but it definitely did not work.

**Comment by hyperknot** [comment]
Right now the only workaround is to install 2.4.2 using brew. 

```
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/a33df1f6b31fb36ae551ac5adda6ce48a61eec01/Formula/gdal.rb
```

does it.

**Comment by FreelanceDev217** [comment]
Thank you.
I was just able to use 2.4.4 with the normal GDAL package. 
For GDAL `brew install gdal` and for Python binding used `pip install gdal==2.4.4`

**Comment by dezhin** [comment]
Just added version 2.4.4 to the repository and PyPi.
