### ISSUE TITLE
Consider inclusion of *.py gdal scripts

### ISSUE THREAD

**Issue by Chrismarsh** [nextgis/pygdal#52]
Is it possible to also include the .py scripts that come with the GDAL python bindings? E.g., gdal_calc.py, etc.

https://github.com/OSGeo/gdal/tree/88bd33c61387c4b0a8ab069106248d8893a2d0a6/gdal/swig/python/scripts

It is odd to have to install the core gdal python bindings (or the system `python-gdal` variants) to get access to these. 

If I `pip install gdal && pip install pygdal` in a virtualenv so-as to have access to the gdal python scripts, it's unclear to me which python binding is loaded -- pygdal or gdal?

**Comment by dezhin** [comment]
I don't think that it's good idea. GDAL python utilities like gdal_calc.py are parts of GDAL package itself like binary utilities (gdalwarp, gdal_translate etc).

The main problem that pygdal package solves is installation to a virtualenv. Usually you don't need to install pygdal as system-wide python package. Anyway, you can check which package is loaded using python:

``` python
import osgeo.gdal
print(osgeo.gdal.__file__)
```
