### ISSUE TITLE
OSError: libx265.so.165: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ldng** [nextgis/pygdal#62]
When installing pygdal in a python 3.6 virtualenv on debian 11 (bullseye) and
try to import it, it generates the following error :
OSError: libx265.so.165: cannot open shared object file: No such file or directory

Could be a libx265 issue in Debian though.
```bash
$ pyenv --version
pyenv 2.0.0
```

It's used to create a Python 3.6 virtualenv
```bash
pip --version
pip 21.1.2 from /home/$foo/.pyenv/versions/3.6.13/envs/$bar/lib/python3.6/site-packages/pip (python 3.6)
```

When cloning the repo and compiling in the 3.2.1 with `python setup.py bdist_wheel`
it seems to link to an unexisting library :
```bash
$ ldd build/lib.linux-x86_64-3.6/osgeo/_gdal.cpython-36m-x86_64-linux-gnu.so 
...
	libde265.so.0 => /usr/lib/x86_64-linux-gnu/libde265.so.0 (0x00007fe1a8d39000)
	libx265.so.165 => not found
	libdav1d.so.4 => /usr/lib/x86_64-linux-gnu/libdav1d.so.4 (0x00007fe1a8c03000)
...
```

The library available is : /usr/lib/x86_64-linux-gnu/libx265.so.192

**Comment by dezhin** [comment]
Unfortunately, I don't have Debian 11 installation at hand. Could you create Dockerfile which reproduces the problem?

**Comment by ldng** [comment]
Good idea, that would also help determine if my specific installation is the actual problem. I'll give it a shot when I find the time.

**Comment by ldng** [comment]
That was actually an issue with a locally compiled libheif that was linked to an old version of libx265. Sorry for the noise.
