### ISSUE TITLE
error installing version 3.3.1.7 in conda env

### ISSUE THREAD

**Issue by digitalw** [nextgis/pygdal#66]
Hi,
When trying to install in to a conda environment I get the error 
```
...
    self.finalize_options()
  File "/tmp/easy_install-orkw7_78/pygdal-3.3.1.7/setup.py", line 124, in finalize_options
  File "/tmp/easy_install-orkw7_78/pygdal-3.3.1.7/setup.py", line 25, in get_numpy_include
AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'
```
Versions:
gdal: 3.0.4
Python 3.6.3 :: Anaconda, Inc.

any help very welcome.

**Comment by dezhin** [comment]
Strangely, you are trying to install pygdal 3.3.1 while you have gdal 3.0.4. You could have installed pygdal==3.0.4.* as README says. But it isn't related to the problem I think.

I don't have conda environment, so could you provide a sample Dockerfile that reproduces the problem?
