### ISSUE TITLE
GeoTiff File getting deleted..!! Error re-writing a tif file (i.e., where the destination filename already existing in the output location) using CreateCopy() method. 

### ISSUE THREAD

**Issue by GSAIVENKAT** [nextgis/pygdal#72]
Hi,
I'm trying to rewrite a tif file by modifying its information with the code below, however when I check for existing data, I get this issue. It has gotten completely damaged and contains no data. It was just lowered from 500mb to 33kb..
Actually, I'm attempting to change metadata using the gdal approach, but I'm unable to properly write the data into it. So, to get around this problem, I'm trying to make a copy and then write metadata, which works fine until I use "save a copy " with any other name but the current filename, which doesn't work (i.e., re-writing). However, I would expect there to be no data loss when an error occurs, but in reality, the original data is erased, which is really disappointing.

code:
dst_ds = driver.CreateCopy( dst_filename.strip('"'), src_ds, 0 )

Output:
  File "C:\Users\SaiVenkatGajaveli\anaconda3\lib\site-packages\osgeo\gdal.py", line 1869, in CreateCopy
    return _gdal.Driver_CreateCopy(self, *args, **kwargs)

RuntimeError: Deleting C:\Geospoc_Works\MaxarData_reflectance_script_task(RDR-10)\Data\Sample_8_bandImage\014197321010_01\014197321010_01_P001_MUL\21FEB06055421-M2AS_R1C1-014197321010_01_P001_Radiance3_meta.TIF failed:
Permission denied

**Comment by dezhin** [comment]
Hi, pygdal is just a convenient way to install GDAL bindings into a virtualenv. I don't think that it's a packaging issue. But if you think so, could you try to do the same with the original system-wide installed GDAL bindings? I think the result will be the same. Otherwise, let me know.
