### ISSUE TITLE
pygdal fails to install via poetry

### ISSUE THREAD

**Issue by AndrewGuenther** [nextgis/pygdal#79]
When attempting to run `poetry install pygdal=="$(gdal-config --version).*"` you'll consistently see the following error:

```
AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'
```

This is being thrown from this line in the setup:
https://github.com/nextgis/pygdal/blob/master/setup.py#L30

```python
def get_numpy_include():
    # Fix numpy installation using setuptools
    __builtins__.__NUMPY_SETUP__ = False  # This line

    import numpy
    return numpy.get_include()
```

This is because `poetry` doesn't execute `setup.py` as `__main__` which results in inconsistent behavior of the `__builtins__` global. The fix for this is a pretty simple wrapper around `__builtins__` access which handles both the `__main__` and non-`__main__` behavior.

```python
def set_builtin(name, value):
    if isinstance(__builtins__, dict):
        __builtins__[name] = value
    else:
        setattr(__builtins__, name, value)
```

**Comment by AndrewGuenther** [comment]
@dezhin any chance you could do a patch release with this on gdal 3.0.4? That's the version currently shipping on Ubuntu 20.04 LTS

**Comment by dezhin** [comment]
Sure, I've released a patch version for 3.0.4.

**Comment by AndrewGuenther** [comment]
We've got some machines running Ubuntu 18.04 LTS (which is still supported) and running gdal 2.2.3, could we get a patch release for that version as well @dezhin? :grimacing: (I promise that's the last one, we don't have anything running 16.04 LTS, I checked)

**Comment by dezhin** [comment]
I missed the notification( I've done the 2.2.3.11 release and it should work now.

**Comment by AndrewGuenther** [comment]
Thank you so much!

**Comment by paysonwallach** [comment]
Apologies in advance, but would it be possible to have a patch release for 3.2.2, as well? It is the system version on the current stable version of Debian.

**Comment by dezhin** [comment]
3.2.2 - published.
