### ISSUE TITLE
pygdal fails to install on python 3.11 

### ISSUE THREAD

**Issue by moaxey** [nextgis/pygdal#83]
I think this is a setuptools/PEP517/518 issue.

```
$ pip install  --use-pep517 pygdal
Collecting pygdal
  Downloading pygdal-3.5.1.11.tar.gz (491 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 492.0/492.0 kB 6.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      running dist_info
      creating /tmp/pip-modern-metadata-xl3uxkcw/pygdal.egg-info
      writing /tmp/pip-modern-metadata-xl3uxkcw/pygdal.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-modern-metadata-xl3uxkcw/pygdal.egg-info/dependency_links.txt
      writing requirements to /tmp/pip-modern-metadata-xl3uxkcw/pygdal.egg-info/requires.txt
      writing top-level names to /tmp/pip-modern-metadata-xl3uxkcw/pygdal.egg-info/top_level.txt
      writing manifest file '/tmp/pip-modern-metadata-xl3uxkcw/pygdal.egg-info/SOURCES.txt'
      error: [Errno 2] No such file or directory: 'gdal-config'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.

```

**Comment by TracyWel** [comment]
I'm running into something similar trying to build a Docker container:

Docker build file:
FROM python:3.11-buster

WORKDIR ./

RUN apt-get update
RUN apt-get install -y software-properties-common
RUN apt-get install -y gdal-bin
RUN apt-get install -y libgdal-dev
RUN export CPLUS_INCLUDE_PATH=/usr/include/gdal
RUN export C_INCLUDE_PATH=/usr/include/gdal
RUN apt-get install -y python-gdal

COPY requirements_agl.txt ./
RUN pip install -r requirements_agl.txt
___

requirements_agl.txt:
DateTime
make
setuptools
numpy
pygdal==2.4.0.10
elevation
rasterio
pandas
typing
docker
build

___

docker build -f Dockerfile_agl_main_py311 -t agl_image_py311 .

___

Result
...
#15 47.99   Running setup.py install for pygdal: started
#15 50.14   Running setup.py install for pygdal: finished with status 'error'
#15 50.16   error: subprocess-exited-with-error
#15 50.16
#15 50.16   × Running setup.py install for pygdal did not run successfully.
#15 50.16   │ exit code: 1
#15 50.16   ╰─> [176 lines of output]
#15 50.16       running install
#15 50.16       /usr/local/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
#15 50.16         warnings.warn(
#15 50.16       running build
#15 50.16       running build_py
...
more after this, but I don't think it's relevant.

___

It builds ok with python:3.9-buster and python:3.10-buster, but not with python:3.11-buster (or 3.11.1)

**Comment by dezhin** [comment]
@TracyWel, it looks like you're trying to use the completely outdated version of GDAL (2.4) with Python 3.11. It's strange and won't success.

**Comment by dezhin** [comment]
@moaxey, it can't find `gdal-config` binary which is required.
